In [22]:
import warnings
warnings.filterwarnings('ignore')

In [23]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [24]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [25]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [26]:
# Load the data
file_path = Path('../LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2= pd.get_dummies(df)
df2.head()
df2.columns

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'issue_d_Feb-2019', 'issue_d_Jan-2019', 'issue_d_Mar-2019',
       'loan_status_high_risk', 'loan_status_low_risk', 'pymnt_plan_n',
       'initial_list_status_f', 'initial_list_status_w',
       'next_pymnt_d_Apr-2019', 'next_pymnt_d_May-2019',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'debt_settlement_flag_N'],
      dtype='object')

In [17]:
# Create our features

x_cols = [i for i in df2.columns if i not in ('loan_status_high_risk','loan_status_low_risk')]
X = df2[x_cols]
#X=df.copy()
#X=X.drop("loan_status", axis=1)
 

# Create our target
y = df2['loan_status_low_risk']
X.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,1,1,0,1,0,1,1,0,1,1

In [18]:
y[:5]

0    1
1    1
2    1
3    1
4    1
Name: loan_status_low_risk, dtype: uint8

In [15]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [14]:
# Check the balance of our target values
#y['loan_status'].value_counts()
y.value_counts()

1    68470
0      347
Name: loan_status_low_risk, dtype: int64

In [19]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1,stratify=y)
Counter(y_train)

Counter({1: 51352, 0: 260})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [21]:
# Resample the training data with the RandomOversampler
from imblearn.ensemble import BalancedRandomForestClassifier
model = BalancedRandomForestClassifier(n_estimators=100, random_state=1)
model.fit(X_train, y_train)

BalancedRandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                               criterion='gini', max_depth=None,
                               max_features='auto', max_leaf_nodes=None,
                               max_samples=None, min_impurity_decrease=0.0,
                               min_samples_leaf=2, min_samples_split=2,
                               min_weight_fraction_leaf=0.0, n_estimators=100,
                               n_jobs=None, oob_score=False, random_state=1,
                               replacement=False, sampling_strategy='auto',
                               verbose=0, warm_start=False)

In [27]:
# Calculated the balanced accuracy score
# 0.7855052723466922
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.787628267884985

In [31]:
# Display the confusion matrix
# array([[   68,    33],
#       [ 1749, 15355]])
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["High Risk Actual", "Low Risk Actual"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm_df

                  Predicted High Risk  Predicted Low Risk
High Risk Actual                   57                  30
Low Risk Actual                  1368               15750

In [30]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.04      0.66      0.92      0.08      0.78      0.59        87
          1       1.00      0.92      0.66      0.96      0.78      0.62     17118

avg / total       0.99      0.92      0.66      0.95      0.78      0.62     17205

BalancedRandomForestClassifier is another ensemble method in which each tree of the forest will be provided a balanced bootstrap sample. Here there are 100 trees and 1 as random generator

In [32]:
# List the features sorted in descending order by feature importance
sorted(zip(model.feature_importances_, X.columns), reverse=True)

[(0.08322179913812433, 'total_rec_prncp'),
 (0.06904406031487648, 'total_pymnt_inv'),
 (0.061119989899441445, 'last_pymnt_amnt'),
 (0.058548908426995186, 'total_pymnt'),
 (0.053533353543796965, 'total_rec_int'),
 (0.024983496691326382, 'int_rate'),
 (0.019778302927070328, 'issue_d_Jan-2019'),
 (0.019417736993910733, 'annual_inc'),
 (0.019361197600498585, 'mths_since_recent_inq'),
 (0.0171406647342267, 'installment'),
 (0.016803047399151203, 'dti'),
 (0.016300306799555686, 'max_bal_bc'),
 (0.016230500875251835, 'total_bal_ex_mort'),
 (0.016129034088648114, 'out_prncp_inv'),
 (0.015579740884554702, 'bc_util'),
 (0.015164908127878355, 'out_prncp'),
 (0.014998138554090453, 'tot_cur_bal'),
 (0.014728071925908266, 'bc_open_to_buy'),
 (0.0143196998590605, 'revol_bal'),
 (0.014108101920311658, 'tot_hi_cred_lim'),
 (0.013722343041258588, 'mo_sin_old_il_acct'),
 (0.01369392475506548, 'total_bc_limit'),
 (0.013039836869296295, 'loan_amnt'),
 (0.013009935637577066, 'total_rev_hi_lim'),
 (0.012700843400061678, 'il_util'),
 (0.01269690262074915, 'mths_since_rcnt_il'),
 (0.012613045234255767, 'mths_since_recent_bc'),
 (0.01260646594424522, 'total_bal_il'),
 (0.012395887357340077, 'avg_cur_bal'),
 (0.011566516897064845, 'all_util'),
 (0.011167573997444048, 'num_rev_accts'),
 (0.01108849352576069, 'total_acc'),
 (0.010983946332038872, 'pct_tl_nvr_dlq'),
 (0.010980340926018625, 'issue_d_Mar-2019'),
 (0.010774641895227763, 'mo_sin_old_rev_tl_op'),
 (0.01017673227356227, 'num_rev_tl_bal_gt_0'),
 (0.00969548739312896, 'num_sats'),
 (0.009623042455678172, 'total_il_high_credit_limit'),
 (0.009328128071085523, 'num_op_rev_tl'),
 (0.00918384660919296, 'mo_sin_rcnt_rev_tl_op'),
 (0.009026150605454336, 'inq_last_12m'),
 (0.008996103164405363, 'num_actv_rev_tl'),
 (0.00896355212700574, 'total_cu_tl'),
 (0.008733423997089361, 'num_actv_bc_tl'),
 (0.008293102095106175, 'percent_bc_gt_75'),
 (0.00784159704520907, 'num_il_tl'),
 (0.007780378232536949, 'acc_open_past_24mths'),
 (0.007669490178939439, 'num_bc_sats'),
 (0.007503720322293207, 'open_acc'),
 (0.0073912940651184875, 'num_tl_op_past_12m'),
 (0.007293743232207529, 'num_bc_tl'),
 (0.006592426895648844, 'open_act_il'),
 (0.006557348998020704, 'inq_fi'),
 (0.006182541853409991, 'next_pymnt_d_May-2019'),
 (0.005973158507068744, 'mo_sin_rcnt_tl'),
 (0.005836361938607466, 'open_il_24m'),
 (0.005661090094467191, 'open_acc_6m'),
 (0.005078872285836077, 'mort_acc'),
 (0.004957696458088384, 'total_rec_late_fee'),
 (0.004944534838544866, 'open_rv_24m'),
 (0.0046309733684305205, 'issue_d_Feb-2019'),
 (0.004613494077587252, 'open_il_12m'),
 (0.004370619295858034, 'next_pymnt_d_Apr-2019'),
 (0.004101765768229515, 'delinq_2yrs'),
 (0.004064944787653854, 'inq_last_6mths'),
 (0.003533532394392628, 'tot_coll_amt'),
 (0.00278991197382569, 'open_rv_12m'),
 (0.002353582438977561, 'num_accts_ever_120_pd'),
 (0.0021281418130302985, 'home_ownership_OWN'),
 (0.0019410627139546167, 'verification_status_Not Verified'),
 (0.001897123625804812, 'verification_status_Source Verified'),
 (0.00187033770798835, 'home_ownership_RENT'),
 (0.0017758057246081474, 'home_ownership_MORTGAGE'),
 (0.0014211142427185373, 'pub_rec_bankruptcies'),
 (0.001100534330185994, 'application_type_Individual'),
 (0.001053823002408795, 'verification_status_Verified'),
 (0.0009961824546662718, 'application_type_Joint App'),
 (0.000964542914474753, 'initial_list_status_f'),
 (0.0008099699906688499, 'pub_rec'),
 (0.00046161504895032195, 'initial_list_status_w'),
 (0.0002853394497971013, 'num_tl_90g_dpd_24m'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'home_ownership_ANY'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collections_12_mths_ex_med'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'chargeoff_within_12_mths'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [33]:
# Train the Classifier
from imblearn.ensemble import EasyEnsembleClassifier
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)
eec.fit(X_train, y_train)

EasyEnsembleClassifier(base_estimator=None, n_estimators=100, n_jobs=None,
                       random_state=1, replacement=False,
                       sampling_strategy='auto', verbose=0, warm_start=False)

In [39]:
# Calculated the balanced accuracy score
# 0.9316600714093861
from sklearn.metrics import balanced_accuracy_score
y_pred_ES = eec.predict(X_test)
balanced_accuracy_score(y_test, y_pred_ES)

0.925427358175101

In [40]:
# Display the confusion matrix
# array([[   93,     8],
#        [  983, 16121]])

from sklearn.metrics import confusion_matrix
cm2=confusion_matrix(y_test, y_pred_ES)
# Create a DataFrame from the confusion matrix.
cm2_df = pd.DataFrame(
    cm2, index=["High Risk Actual", "Low Risk Actual"], columns=["Predicted High Risk", "Predicted Low Risk"])

cm2_df

                  Predicted High Risk  Predicted Low Risk
High Risk Actual                   79                   8
Low Risk Actual                   979               16139

In [42]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred_ES))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.07      0.91      0.94      0.14      0.93      0.85        87
          1       1.00      0.94      0.91      0.97      0.93      0.86     17118

avg / total       0.99      0.94      0.91      0.97      0.93      0.86     17205

In ensemble classifiers, boosting - it takes into consideration errors from the previous trees.